version: "3"
services:
  panel:
    build:
      context: ./panel
      args:
        panel_ver: v0.7.18
    # Edit the follwing line to use your own custom command
    command: [ "/usr/local/sbin/php-fpm", "--nodaemonize" ]
    env_file: ./panel/panel.env
    restart: unless-stopped
    tty: true
    volumes:
      # App key file
      - ./panel/data/appkey.env:/panel/appkey.env
      # Storage
      - ./panel/data/storage:/panel/storage
      # Cache
      - ./panel/data/bootstrap/cache:/panel/bootstrap/cache
      # Public
      - ./panel/data/public:/panel/public
    ports:
      - 9000:9000
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 29900:80
    depends_on:
      - panel
  redis:
    image: redis:alpine
    restart: unless-stopped
  mysql:
    image: mariadb:latest
    env_file: ./mysql/mysql.env
    restart: unless-stopped
    volumes:
      - ./mysql/db:/var/lib/mysql
