version: "3"
services:
  panel:
    build:
      context: .
      args:
        mysql_db: "pterodactyl"
        mysql_user: "pterodactyl"
        mysql_password: "testpass"
    restart: unless-stopped
    volumes:
      - ./data/pterodactyl:/var/www/pterodactyl
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - "29900":"80"
      - "29901":"443"
