version: "3"
services:
  panel:
    build:
      context: ./panel
    environment:
      MYSQL_USER: "pterodactyl"
      MYSQL_PASSWORD: ""
    restart: unless-stopped
    tty: true
    volumes:
      - ./panel/panel-data:/var/www/pterodactyl
    ports:
      - 9000:9000
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - 29900:80
    depends_on:
      - panel
  redis:
    image: redis:alpine
    restart: unless-stopped
  mysql:
    image: mariadb:latest
    env_file: ./mysql/mysql.env
    restart: unless-stopped
    volumes:
      - ./mysql/db:/var/lib/mysql
