#!/bin/sh

# This script is ran on container start.
#
# It initialises various things, including:
# some basic file / dir cleanup,
# first time db setup,
# crontab configuration,
# and more.

echo "################################"
echo "## STARTING ENTRYPOINT SCRIPT ##"
echo "################################"

# Ensure correct dir
cd /panel

# Create needed dirs if not exist
if find ./storage -mindepth 1 | read; then
    echo -e "\nStorage dir is empty!"
    mkdir -p storage
    cat .storage.template | while read line; do
        mkdir -p "/panel/${line}"
        echo "created ${line}"
    done
fi

# Set permissions for storage/framework
chmod -R 775 storage/framework

# Check for config file
if [ ! -s ptero.env ]; then
    echo ""
    echo "######################"
    echo "## first time setup ##"
    echo "######################"
    echo ""
    echo "Initiating first time setup, as ptero.env is empty."
    sleep 1

    echo -e "\nGenerating ptero.env file"
    touch ptero.env
    echo "# Do not use the .env file!" >> /panel/ptero.env
    echo "# Use environment variables instead!" >> /panel/ptero.env
    echo "# " >> /panel/ptero.env
    echo "# This file is automatically generated and contains the app key," >> /panel/ptero.env
    echo "# used to encrypt sensitive information." >> /panel/ptero.env
    echo "" >> /panel/ptero.env
    echo "APP_KEY=SomeRandomString3232RandomString" >> /panel/ptero.env

    echo -e "\nMaking symlink"
    sleep 1
    ln -s /panel/ptero.env .env

    echo -e "\nGenerating key..."
    sleep 1
    php artisan key:generate --force --no-interaction

    echo -e "\nCreating & seeding database..."
    sleep 1
    php artisan migrate --force
    php artisan db:seed --force

    echo -e "\n## FIRST TIME SETUP DONE! ##"
fi

echo -e "\n## INITIALISATION IS FINISHED! ##"
